### ISSUE TITLE
bug: 'undo' works but still display a new card

### ISSUE THREAD

**Issue by madcc** [feilongfl/ankiview-vscode#31]
**Describe the bug**
After answering card A, the front of next card B is displayed. then I click 'z' to undo answering card A, but the view is still card B, instead of backing to card A. If I click space and answer on the current card B, Anki (not ankiview-vscode) will pop up a windows with "not at top of queue", then I click OK and back to vscode, the ankiview still shows front of card B (actually the current card is card A, but the view is not  refreshed, thus shows card B), and if I click space now, then back of card A is displayed and I can answer card A normally.
So 'undo' has succeed, but has not gone back to last card immediately and the view content is not refreshed. 

**To Reproduce**
1. Answer card A, then front of card B is displayed. 
2. Press 'z' to undo, still card B, while I expect to go back to front of card A.
3. I click space to see back of card B, and try to answer it, then 'Anki' pop up a window with "not at top of queue", click OK to close that windows.
4. Going back to vscode, still display card B while actually card A. Here the view is not refreshed, I expected to see front of card A.
5. Click 'space', then display back of card A.

**Desktop (please complete the following information):**
 - OS: mac OS
 - Anki Version: Version ⁨24.06.2 (33a92379)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
 - AnkiView Version: 0.0.9

Btw, I have 'guiUndo' function in 'AnkiConnect' plugin.

**Comment by feilongfl** [comment]
I was able to reproduce this issue, but I found that it is not a problem with anki-view. 

Instead, the issue lies in anki-connect where the `guiCurrentCard` interface does not correctly refresh the current card before returning the information.

To fix this issue, I created the following patch. Unfortunately, I discovered that the repository has been moved to https://git.foosoft.net/alex/anki-connect, so we can't directly submit a PR for the fix. I will try to contact the maintainer of anki-connect via email to attempt to merge this patch. In the meantime, please manually modify the code as follows:

1. Open Anki's plugin window and navigate to the anki-connect file directory.

2. Modify __init__.py and add the following code in the `guiCurrentCard` function:

``` diff
 def guiCurrentCard(self):
        if not self.guiReviewActive():
            raise Exception('Gui review is not currently active.')

        reviewer = self.reviewer()
+        reviewer.refresh_if_needed()
        card = reviewer.card
        model = card.note_type()
        note = card.note()
 ...
```

---

patch file

``` patch
From aee6331c643130384a289d1795db97a62820b803 Mon Sep 17 00:00:00 2001
From: YuLong Yao <feilongphone@gmail.com>
Date: Sun, 14 Jul 2024 19:12:03 +0800
Subject: [PATCH] guiCurrentCard: Call refresh_if_needed to refresh the card
 before returning card info.

If undo/redo is called by the user, the current card will be outdated if we don't refresh it.

Signed-off-by: YuLong Yao <feilongphone@gmail.com>
---
 plugin/__init__.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/plugin/__init__.py b/plugin/__init__.py
index c4b59fc..c9bc5b9 100644
--- a/plugin/__init__.py
+++ b/plugin/__init__.py
@@ -1877,6 +1877,7 @@ class AnkiConnect:
             raise Exception('Gui review is not currently active.')
 
         reviewer = self.reviewer()
+        reviewer.refresh_if_needed()
         card = reviewer.card
         model = card.note_type()
         note = card.note()
-- 
2.45.2


```

**Comment by madcc** [comment]
Thanks, the 'undo' is OK now.

I have found another problem sometimes **before** fixing this 'undo' bug: After answering one card A, the view still show front of card A instead of front of next card B. while I click space to see back, it shows back of next card B! Thus the front view is not refreshed in time.
Maybe this bug is also caused by  not calling 'reviewer.refresh_if_needed()' ?
It happens just sometimes, maybe once every 10~30 cards. and I have added a delay to suppress this bug and it seems to work:
```
public async answerCard(ease: number, autoEase: boolean = false) {
        .....;
+      await new Promise(f => setTimeout(f, 100));
	this.showQuestion();
	return true;
```

**Comment by feilongfl** [comment]
Because I haven't upgraded Anki on my personal computer, I am using a relatively old version. When you reported this bug, I installed the new version on a development computer for testing.

In previous versions of Anki, the interface could refresh in real time. I suspect that in a later version, Anki reduced the frequency of graphical interface refreshes when it is not in the foreground (which is reasonable as it reduces performance consumption).

Additionally, since I mainly use the old version, it would be more cumbersome for me to test bugs that require some time to reproduce on the new version. 

However, if the problem still occurs after adding refresh_if_needed, I am very willing to help investigate further.

**Comment by madcc** [comment]
Thanks, It works for me enough now, and you don't need to test it specifically.
